### ISSUE TITLE
Error when Debug is True

### ISSUE THREAD

**Issue by urusd** [rosette-api/python#102]
https://github.com/rosette-api/python/blob/0ab6df0f0b41dde8ded400e92807634c62393e0c/rosette/api.py#L499

When you set "debug=True" in API(service_url="http://localhost:8181/rest/v1/", debug=True) you get Error:
`
Exception has occurred: InvalidHeader
Header part (True) from {'X-RosetteAPI-Devel': True} must be of type str or bytes, not <class 'bool'>
`

**Comment by seth-mg** [comment]
Released with 1.25.1
