### ISSUE TITLE
Importing API overrides user warning filters

### ISSUE THREAD

**Issue by KennyChenBasis** [rosette-api/python#119]
Line https://github.com/rosette-api/python/blob/e32db6392003b60c0efad5dd238479681c019ab3/rosette/api.py#L49 overrides user warning filters. This should not happen since the user may want certain warnings (e.g. `DeprecationWarning`) filtered, and those filters may be set in `pytest.ini_options` (i.e. before importing `rosette.api`).

**Comment by Katsuya-Tomioka** [comment]
Can you open a PR?
