### ISSUE TITLE
Cannot set "options" parameter in Python client

### ISSUE THREAD

**Issue by giang-nghg** [rosette-api/python#61]
The Python wrapper prevent adding the "options" parameter while it is a valid param. The API does not complain when I send the request with an "options" parameter with curl, but the wrapper raise an exception when I try to set it to the request's params. I saw that using the [`serialize`](https://github.com/rosette-api/python/blob/develop/rosette/api.py#L201) method you can add options, but the comment in source says it's for internal use.

https://github.com/rosette-api/python/blob/develop/rosette/api.py#L181

**Comment by guruxu** [comment]
Yes, the `serialize` function is for internal use. To add a call option you would use the `setOption` method on the `API` class. For example: `api.setOption("linkEntities", False)`.
