### ISSUE TITLE
Bindings should allow specifying get parameters

### ISSUE THREAD

**Issue by talolard** [rosette-api/python#95]
# Use Case
The REST API allows specifying REST paramaters. Notably, the entities endpoint supports `?output=rosette` which returns sentences, tokens and analysis along with entities. I want to use that with the bindings. 

# Problem 
The bindings don't seem to support specifying parameters.  
The [EndpointCaller creates a payload](https://github.com/rosette-api/python/blob/6a0d4712ff4297dc4cd9457ba8d3e71b89b91cca/rosette/api.py#L492) which references any [set url paramaters](https://github.com/rosette-api/python/blob/6a0d4712ff4297dc4cd9457ba8d3e71b89b91cca/rosette/api.py#L754) but there doesn't seem to be a way to set them from the entities method

**Comment by seth-basistech** [comment]
Hi @talolard.
Is this still required?

**Comment by talolard** [comment]
I don't need it.
But I stopped using the bindings because they aren't useful without these

**Comment by seth-mg** [comment]
Yeah, you have to enable it on the `api` object.
```
api = API()
entities_text_data = "Some sample text for entities"
params = DocumentParameters()
params["content"] = entities_text_data
api.set_url_parameter("output", "rosette")
api.entities(params)
```
